# Análise Exploratória de Dados / Exploratory Data Analysis (EDA)

Uma boa EDA (Exploratory Data Analysis) pode ser pensada como uma sequência de perguntas que você faz ao dataset antes de partir para conclusões, visualizações mais sofisticadas ou Machine Learning.

- Um analista de dados é como um detetive: observa as pistas, encontra padrões e desvenda o que está por trás dos números.
- Dados são pistas. Padrões são evidências. E você é quem vai solucionar o mistério.
- Você não precisa de uma lupa para ser investigador — basta saber fazer as perguntas certas aos dados.


**Nos tempos dos reis, o conselheiro trazia informações para ajudar o governante a decidir. Hoje, o analista faz isso com dados. O rei tinha seus conselheiros. Hoje, empresas e organizações têm analistas de dados: pessoas que transformam informações em decisões.**

**Um analista de dados é como o conselheiro de um rei: transforma informações em conhecimento para orientar decisões importantes.**

# 0. Vamos começar. Primeiro importe pandas e os dados.

In [1]:
import pandas as pd

In [2]:
# Leia seu arquivo csv aqui

df = pd.read_csv("marvel.csv")

#### O próximo passo é dividir o processo em etapas

## 1. Entendimento geral do dataset

Antes de analisar os dados, descubra o que você recebeu.

### Qual é a unidade de observação? Uma pessoa? Uma venda? Um crime? Um dia?

Personagens

### Qual é a origem dos dados?

kaggle

### Quantas linhas e colunas existem?

In [6]:
df.shape

(16376, 11)

### O que cada coluna representa?

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16376 entries, 0 to 16375
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              16376 non-null  str
 1   ID                12606 non-null  str
 2   ALIGN             13564 non-null  str
 3   EYE               6609 non-null   str
 4   HAIR              12112 non-null  str
 5   SEX               15522 non-null  str
 6   GSM               90 non-null     str
 7   ALIVE             16373 non-null  str
 8   APPEARANCES       15280 non-null  float64
 9   FIRST APPEARANCE  15561 non-null  str
 10  Year              15561 non-null  float64
dtypes: float64(2), str(9)
memory usage: 2.9 MB

### Qual é o período coberto pelos dados?

In [11]:
df['Year'].min(), df['Year'].max()

(np.float64(1939.0), np.float64(2013.0))

In [12]:
df['Year'].nunique()

75

### Existem identificadores únicos?

In [ ]:
não

### Existem colunas que parecem redundantes?

In [13]:
df[['APPEARANCES','FIRST APPEARANCE']]

       APPEARANCES FIRST APPEARANCE
0           4043.0           Aug-62
1           3360.0           Mar-41
2           3061.0           Oct-74
3           2961.0           Mar-63
4           2258.0           Nov-50
...            ...              ...
16371          NaN              NaN
16372          NaN              NaN
16373          NaN              NaN
16374          NaN              NaN
16375          NaN              NaN

[16376 rows x 2 columns]

# 2. Tipos e estrutura das variáveis(colunas)

Para cada coluna:
- Ela é numérica, categórica, texto, data/hora ou booleana?
- O tipo armazenado corresponde ao tipo real da informação? Exemplo: Existem números armazenados como texto?
- Existem datas armazenadas como strings? 
- Existem categorias com grafias diferentes?
```text
    Exemplo:
    - "São Paulo"
    - "Sao Paulo"
    - "são paulo"
    Podem representar a mesma categoria.
```

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16376 entries, 0 to 16375
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              16376 non-null  str
 1   ID                12606 non-null  str
 2   ALIGN             13564 non-null  str
 3   EYE               6609 non-null   str
 4   HAIR              12112 non-null  str
 5   SEX               15522 non-null  str
 6   GSM               90 non-null     str
 7   ALIVE             16373 non-null  str
 8   APPEARANCES       15280 non-null  float64
 9   FIRST APPEARANCE  15561 non-null  str
 10  Year              15561 non-null  float64
dtypes: float64(2), str(9)
memory usage: 2.9 MB

In [16]:
df.head()

,name,ID,ALIGN,EYE,HAIR,SEX,GSM,ALIVE,APPEARANCES,FIRST APPEARANCE,Year
0,Spider-Man (Peter Parker),Secret Identity,Good Characters,Hazel Eyes,Brown Hair,Male Characters,NaN,Living Characters,4043.0,Aug-62,1962.0
1,Captain America (Steven Rogers),Public Identity,Good Characters,Blue Eyes,White Hair,Male Characters,NaN,Living Characters,3360.0,Mar-41,1941.0
2,"Wolverine (James \""Logan\"" Howlett)",Public Identity,Neutral Characters,Blue Eyes,Black Hair,Male Characters,NaN,Living Characters,3061.0,Oct-74,1974.0
3,"Iron Man (Anthony \""Tony\"" Stark)",Public Identity,Good Characters,Blue Eyes,Black Hair,Male Characters,NaN,Living Characters,2961.0,Mar-63,1963.0
4,Thor (Thor Odinson),No Dual Identity,Good Characters,Blue Eyes,Blond Hair,Male Characters,NaN,Living Characters,2258.0,Nov-50,1950.0

# 3. Dados ausentes

Uma das perguntas mais importantes:

- Onde estão os dados faltantes e por que estão faltando?

### Existem valores NaN? Quantos por coluna?

dica: df.isna().sum()

In [19]:
df.isna().sum()

name                    0
ID                   3770
ALIGN                2812
EYE                  9767
HAIR                 4264
SEX                   854
GSM                 16286
ALIVE                   3
APPEARANCES          1096
FIRST APPEARANCE      815
Year                  815
dtype: int64

### Qual percentual representa? Existem linhas completamente vazias?

dica: (df.isna().mean() * 100).sort_values(ascending=False)

In [20]:
(df.isna().mean() * 100).sort_values(ascending=False)

GSM                 99.450415
EYE                 59.642159
HAIR                26.038105
ID                  23.021495
ALIGN               17.171470
APPEARANCES          6.692721
SEX                  5.214949
Year                 4.976795
FIRST APPEARANCE     4.976795
ALIVE                0.018319
name                 0.000000
dtype: float64

# 4. Duplicidades

Pergunte:

- Existem linhas duplicadas?
- Existem registros duplicados pelo identificador que deveria ser único?
- O que define uma observação como única?
- Duplicatas são erros ou representam eventos legítimos?

dica: df.duplicated().sum()

In [21]:
df.duplicated().sum()

np.int64(0)

# 5.Qualidade e consistência dos dados

Aqui é uma etapa extremamente importante.

Aqui você começa a procurar anomalias.

Perguntas:

- Existem valores impossíveis?
- Existem valores negativos onde não deveriam existir?
- Existem idades de 300 anos?
- Existem datas futuras?
- Existem categorias inesperadas?
- Existem valores 0 que deveriam ser NaN?
- Existem erros de digitação?
- Existem unidades diferentes misturadas?

Exemplo:
```text
idade
-----
21
35
42
-5
999

Ou:

salário
-------
0
3500
4200
-600
5000
3500000


```
**A pergunta não é simplesmente:**

"Esse valor é diferente?"

Mas:

"Esse valor faz sentido dentro do contexto do problema?"

In [22]:
df.describe()

        APPEARANCES          Year
count  15280.000000  15561.000000
mean      17.033377   1984.951803
std       96.372959     19.663571
min        1.000000   1939.000000
25%        1.000000   1974.000000
50%        3.000000   1990.000000
75%        8.000000   2000.000000
max     4043.000000   2013.000000

# 6. Distribuição das variáveis numéricas

Para cada variável numérica:

- Qual é o mínimo?
- Qual é o máximo?
- Qual é a média?

In [42]:
df['APPEARANCES'].min()

np.float64(1.0)

In [55]:
df['Year'].min()

np.int64(1939)

In [43]:
df['APPEARANCES'].max()

np.float64(4043.0)

In [51]:
df['Year'].max()

np.int64(2013)

In [44]:
df['APPEARANCES'].mean()

np.float64(17.033376963350786)

In [54]:
round(df["Year"].mean())

1985

# 7. Distribuição das variáveis categóricas

Para cada variável categórica:

- Quais categorias existem?
- Quantas observações existem em cada categoria?
- Qual é a categoria mais frequente?
- Existem categorias muito raras?
- Existe desbalanceamento?
- Existem categorias inesperadas?

Perguntas importantes:

Existe uma categoria responsável por 90% dos registros?

Existem categorias com apenas 1 ou 2 observações?

Isso pode ser extremamente importante posteriormente.

In [68]:
df.columns

Index(['name', 'ID', 'ALIGN', 'EYE', 'HAIR', 'SEX', 'GSM', 'ALIVE',
       'APPEARANCES', 'FIRST APPEARANCE', 'Year'],
      dtype='str')

In [64]:
df['ALIVE'].nunique()

2

In [73]:
df['name'].value_counts()

name
Spider-Man (Peter Parker)              1
Captain America (Steven Rogers)        1
Wolverine (James \"Logan\" Howlett)    1
Iron Man (Anthony \"Tony\" Stark)      1
Thor (Thor Odinson)                    1
                                      ..
Ru'ach (Earth-616)                     1
Thane (Thanos' son) (Earth-616)        1
Tinkerer (Skrull) (Earth-616)          1
TK421 (Spiderling) (Earth-616)         1
Yologarch (Earth-616)                  1
Name: count, Length: 16376, dtype: int64

In [81]:
df["ID"].value_counts().head(1)

ID
Secret Identity    6275
Name: count, dtype: int64

In [82]:
df["HAIR"].value_counts()[df["HAIR"].value_counts() < 10]

HAIR
Gold Hair             8
Reddish Blond Hair    6
Light Brown Hair      6
Magenta Hair          5
Orange-brown Hair     3
Bronze Hair           1
Dyed Hair             1
Name: count, dtype: int64

In [89]:
(df["ALIVE"].value_counts(normalize=True) * 100).round(2)

ALIVE
Living Characters      77.0
Deceased Characters    23.0
Name: proportion, dtype: float64

In [95]:
df["EYE"].unique()

<ArrowStringArray>
[     'Hazel Eyes',       'Blue Eyes',      'Brown Eyes',      'Green Eyes',
       'Grey Eyes',     'Yellow Eyes',       'Gold Eyes',        'Red Eyes',
  'Black Eyeballs',      'Amber Eyes',   'Variable Eyes',               nan,
      'Black Eyes',      'White Eyes',     'Orange Eyes',     'Silver Eyes',
     'Purple Eyes',       'Pink Eyes',         'One Eye',     'Violet Eyes',
   'Multiple Eyes',    'Magenta Eyes', 'Yellow Eyeballs',         'No Eyes',
   'Compound Eyes']
Length: 25, dtype: str

# 8. Perguntas específicas do domínio

Essa é talvez a parte mais importante.

Você precisa perguntar:

O que é importante nesse problema específico?

Por exemplo:

**Dataset de vendas**

- Qual produto vende mais?
- Qual região vende mais?
- Quando as vendas aumentam?
- Qual produto possui maior faturamento?


**Dataset de crimes**

- Onde ocorrem mais ocorrências?
- Quando ocorrem?
- Quais naturezas predominam?
- Existem diferenças entre bairros?
- Existe concentração geográfica?

**Dataset de estudantes**

- Existe relação entre frequência e nota?
- Quais fatores estão associados à evasão?
- Como as notas variam entre turmas?
- Existe diferença por período?

**Dataset financeiro**

- Como o faturamento evolui?
- Quais produtos geram maior margem de lucro?
- Existem transações anormais?
- Existem valores extremos?

In [ ]:
#Qual é o ano com maior número de aparições de personagens?

df["Year"].value_counts().head()

Year
1993    554
1994    485
1992    455
2006    381
1991    360
Name: count, dtype: Int64

In [103]:
#Como os personagens estão distribuídos de acordo com a categoria GSM?

df["GSM"].value_counts()

GSM
Homosexual Characters     66
Bisexual Characters       19
Transgender Characters     2
Transvestites              1
Pansexual Characters       1
Genderfluid Characters     1
Name: count, dtype: int64

In [104]:
#Qual é a cor dos olhos mais rara entre os personagens?

df["EYE"].value_counts().idxmin()

'Compound Eyes'